#############################################################################
# Makefile for building: untitled1
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? 10? 17 09:26:47 2016
# Project:  untitled1.pro
# Template: app
# Command: /usr/local/Qt-4.8.6-static/bin/qmake -spec /usr/local/Qt-4.8.6-static/mkspecs/linux-g++ CONFIG+=debug -o Makefile untitled1.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Qt-4.8.6-static/mkspecs/linux-g++ -I. -I/usr/local/Qt-4.8.6-static/include/QtCore -I/usr/local/Qt-4.8.6-static/include/QtNetwork -I/usr/local/Qt-4.8.6-static/include/QtGui -I/usr/local/Qt-4.8.6-static/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Qt-4.8.6-static/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Qt-4.8.6-static/lib -lQtGui -L/usr/local/Qt-4.8.6-static/lib -L/usr/X11R6/lib -lpng -lgobject-2.0 -lSM -lICE -lXrender -lfontconfig -lfreetype -lXext -lX11 -lQtNetwork -lQtCore -lz -lm -ldl -pthread -lgthread-2.0 -lglib-2.0 -lrt -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Qt-4.8.6-static/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = /usr/local/Qt-4.8.6-static/mkspecs/common/unix.conf \
		/usr/local/Qt-4.8.6-static/mkspecs/common/linux.conf \
		/usr/local/Qt-4.8.6-static/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-4.8.6-static/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-4.8.6-static/mkspecs/common/g++-base.conf \
		/usr/local/Qt-4.8.6-static/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-4.8.6-static/mkspecs/qconfig.pri \
		/usr/local/Qt-4.8.6-static/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/qt_config.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/default_pre.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/debug.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/default_post.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/static.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/warn_on.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/qt.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/moc.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/resources.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/uic.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/yacc.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/lex.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/include_source_dir.prf \
		untitled1.pro
QMAKE_TARGET  = untitled1
DESTDIR       = 
TARGET        = untitled1

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: untitled1.pro  /usr/local/Qt-4.8.6-static/mkspecs/linux-g++/qmake.conf /usr/local/Qt-4.8.6-static/mkspecs/common/unix.conf \
		/usr/local/Qt-4.8.6-static/mkspecs/common/linux.conf \
		/usr/local/Qt-4.8.6-static/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-4.8.6-static/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-4.8.6-static/mkspecs/common/g++-base.conf \
		/usr/local/Qt-4.8.6-static/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-4.8.6-static/mkspecs/qconfig.pri \
		/usr/local/Qt-4.8.6-static/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/qt_config.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/default_pre.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/debug.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/default_post.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/static.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/warn_on.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/qt.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/moc.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/resources.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/uic.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/yacc.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/lex.prf \
		/usr/local/Qt-4.8.6-static/mkspecs/features/include_source_dir.prf \
		/usr/local/Qt-4.8.6-static/lib/libQtGui.prl \
		/usr/local/Qt-4.8.6-static/lib/libQtCore.prl \
		/usr/local/Qt-4.8.6-static/lib/libQtNetwork.prl
	$(QMAKE) -spec /usr/local/Qt-4.8.6-static/mkspecs/linux-g++ CONFIG+=debug -o Makefile untitled1.pro
/usr/local/Qt-4.8.6-static/mkspecs/common/unix.conf:
/usr/local/Qt-4.8.6-static/mkspecs/common/linux.conf:
/usr/local/Qt-4.8.6-static/mkspecs/common/gcc-base.conf:
/usr/local/Qt-4.8.6-static/mkspecs/common/gcc-base-unix.conf:
/usr/local/Qt-4.8.6-static/mkspecs/common/g++-base.conf:
/usr/local/Qt-4.8.6-static/mkspecs/common/g++-unix.conf:
/usr/local/Qt-4.8.6-static/mkspecs/qconfig.pri:
/usr/local/Qt-4.8.6-static/mkspecs/features/qt_functions.prf:
/usr/local/Qt-4.8.6-static/mkspecs/features/qt_config.prf:
/usr/local/Qt-4.8.6-static/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt-4.8.6-static/mkspecs/features/default_pre.prf:
/usr/local/Qt-4.8.6-static/mkspecs/features/debug.prf:
/usr/local/Qt-4.8.6-static/mkspecs/features/default_post.prf:
/usr/local/Qt-4.8.6-static/mkspecs/features/static.prf:
/usr/local/Qt-4.8.6-static/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Qt-4.8.6-static/mkspecs/features/warn_on.prf:
/usr/local/Qt-4.8.6-static/mkspecs/features/qt.prf:
/usr/local/Qt-4.8.6-static/mkspecs/features/unix/thread.prf:
/usr/local/Qt-4.8.6-static/mkspecs/features/moc.prf:
/usr/local/Qt-4.8.6-static/mkspecs/features/resources.prf:
/usr/local/Qt-4.8.6-static/mkspecs/features/uic.prf:
/usr/local/Qt-4.8.6-static/mkspecs/features/yacc.prf:
/usr/local/Qt-4.8.6-static/mkspecs/features/lex.prf:
/usr/local/Qt-4.8.6-static/mkspecs/features/include_source_dir.prf:
/usr/local/Qt-4.8.6-static/lib/libQtGui.prl:
/usr/local/Qt-4.8.6-static/lib/libQtCore.prl:
/usr/local/Qt-4.8.6-static/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt-4.8.6-static/mkspecs/linux-g++ CONFIG+=debug -o Makefile untitled1.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/untitled11.0.0 || $(MKDIR) .tmp/untitled11.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/untitled11.0.0/ && $(COPY_FILE) --parents mainwindow.h .tmp/untitled11.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp .tmp/untitled11.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/untitled11.0.0/ && (cd `dirname .tmp/untitled11.0.0` && $(TAR) untitled11.0.0.tar untitled11.0.0 && $(COMPRESS) untitled11.0.0.tar) && $(MOVE) `dirname .tmp/untitled11.0.0`/untitled11.0.0.tar.gz . && $(DEL_FILE) -r .tmp/untitled11.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/local/Qt-4.8.6-static/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/local/Qt-4.8.6-static/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

